FROM pegasus/pegasus:centos6

MAINTAINER Rajiv Mayani <mayani@isi.edu>, George Papadimitriou <georgpap@isi.edu>

USER root

RUN yum -y update

# Panorama requirements
RUN yum -y install curl-devel

USER bamboo
